stages:
  - build

build:
  stage: build
  image: docker:latest
  tags:
    - linux
  only:
    - /^docker/ # for testing the pipeline
    - main
  services:
    - docker:dind
  script:
    - docker image prune -a
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
