export const DULICATED_EXCEPTION_MESSAGE = "user with given email address aldeady exist in database";
export const BAD_CONFIRMATION_TOKEN = "bad confirmation token";
export const USER_WITH_GIVEN_EMAIL_IS_NOT_VERIFIED = "user with given email is not verified";
export const USER_WITH_GIVEN_EMAIL_IS_ALREADY_CONFIRMED = "user with given email is already confirmed";
export const INCORRECT_EMAIL_ADDRES_OR_PASSWORD = "incorrect email address or password";
export const INVALID_REFRESH_TOKEN = "invalid refreshToken";
export const INVALID_VERIFICATION_CODE = "invalid verification code";
export const USER_PROVIDED_BY_EXTERNAL_PROVIDER = "user is provided by external provider";
export const OAUTH_USER_NOT_VERIFIED = "Oauth user not verified";